### PR TITLE
add `minimal` parameter to GET /boxes

### PR DESCRIPTION
**Pull request by noerw**
## Description
Trying to speed up the response time of `GET /boxes` with a `minimal` flag:
- minimizing the payload size by omitting non-essential box data
- speeding up DB queries by avoiding expensive lookups (`lastMeasurement`).

To still allow classification of boxes into active/inactive, I tried an alternative approach:
Comparing against `box.updatedAt` instead of `box.sensors[].lastMeasurement.createdAt`.
This yields wrong results for boxes that upload measurements back in time, or when box metadata is updated for inactive boxes.
Because of that, tests are failing.
These should be rather rare cases?

## Motivation and Context
The initial page load time of opensensemap.org is extremely long (14s), limited by the API response time. It seems to be very slow due to `box.sensors[].lastMeasurement` lookups, and will become even slower over time.

## How Has This Been Tested?
I ran minimal tests by hand. This is a prototype.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code has been linted using `yarn run lint`.
- [x] My code does not break the tests (`yarn run test`)
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by noerw** [comment]
Why not, for a clean solution this would be great. We then store a timestamp of the last box update (any changes), last location update (in `currentLocation.timestamp`), and for the last measurement.

**Comment by mpfeil** [comment]
Sounds good to me. Do you have some free time for it? I am on a different project for 1 or 2 weeks.

**Comment by ubergesundheit** [comment]
I like this solution!

**Comment by noerw** [comment]
@mpfeil I merged your `lastMeasurementAt` addition, so this pull only adds the `/boxes?minimal` parameter in addition to your changes.
Also tests are implemented now.

**Comment by noerw** [comment]
Any feedback on this?
The `minimal` parameter decreases payload size of the /boxes request to 40%, and spares the lookup of the sensors (and thus `lastMeasurement`).

**Comment by mpfeil** [comment]
I am going to merge it later this day

**Pull request merged**
