### PR TITLE
store TTN configuration for each box

### PR DESCRIPTION
**Pull request by noerw**
Adds the property `integrations: { mqtt, ttn }` to `box`.

- the schema for `integrations.ttn` is:
    ```js
    {
      // as registered in thethingsnetwork 
      app_id: String,
      dev_id: String,

      // json: data comes in `payload` as JSON in the API's currently consumable JSON schema
      // bytes: data comes in `payload_raw` as byte string, which gets decoded according to a profile
      messageFormat: Enum['json', 'bytes'],
      decodeOptions: {
        // custom: bytes get decoded through a custom byte mask specified in byteMask
        // sensebox/home: the currently only predefined configuration as implemented in
        //                lora/ttnPayloadFunctionExample.js
        profile: Enum['custom', 'sensebox/home'],
        // defines the amount of bytes to consume for each sensor. each element matches one sensor in `box.sensors` in the same order
        byteMask: Array[Number]
      }
    }
    ```

- Breaks the response schema for `GET /users/me/boxes`, as `box.mqtt` is not available anymore.

- The payload format for `PUT /boxes/:boxId` stays as is, in order to avoid breaking changes:
    MQTT & TTN are configured through `{ mqtt: {...}, ttn: {...} }`

### CODE REVIEW

**Comment by noerw** [comment]
The decoder as implemented in sensebox/ttn-osem-application does not support profiles yet, to be implemented.

**Comment by ubergesundheit** [comment]
Alright. If it's okay with you , I'll merge Monday.

**Comment by ubergesundheit** [comment]
One thing: Please use the `named function expression` form for declaring functions. It sets the `.name` property of the function and allows for easier debugging if an error occurs in the function (for honeybadger)

**Comment by ubergesundheit** [comment]
Looks good! Merging now.

**Pull request merged**
